### ISSUE TITLE
ne_countries message:maptools, rgdal, and rgeos, underpinning this package will retire shortly message

### ISSUE THREAD

**Issue by Luigi-Annic** [ropensci/rnaturalearth#106]
I'm running the following line of code:
ne_countries(scale = 50, continent = NULL, returnclass = "sf")

It works, but I get a message that says:
"The legacy packages maptools, rgdal, and rgeos, underpinning this package
will retire shortly. Please refer to R-spatial evolution reports on
https://r-spatial.org/r/2023/05/15/evolution4.html for details.
This package is now running under evolution status 0 ".

I do not fully get the consequences of this message. 
Does it mean that I will need to change something in my code in the near future?
Is there anything I can do to tackle this?

Notably, this message does not appear if I change the scale value to 110.

**Comment by PMassicotte** [comment]
Try installing: 

https://github.com/ropensci/rnaturalearthhires
https://github.com/ropensci/rnaturalearthdata

From GitHub, it should fix it.

**Comment by Luigi-Annic** [comment]
Installing rnaturalearthdata version 1.0.0 from GitHub fixed it!
Do you plan to update this package also in CRAN? I would like to include it in a package of mine (as one of the "suggests"), but when I run the checks a message says

"Package required and available but unsuitable version: 'rnaturalearthdata'"

This makes sense to me, as I see that in CRAN rnaturalearthdata is back to version 0.1.0.
Thank you for your help!

**Comment by PMassicotte** [comment]
We plan to submit both data and hires very soon to CRAN!

**Comment by Luigi-Annic** [comment]
Thanks!
