### ISSUE TITLE
United States missing using geostationary satellite view projection only

### ISSUE THREAD

**Issue by TeresaPegan** [ropensci/rnaturalearth#107]
Hello,
I am using rnaturalearth for its polygons of the western hemisphere. I have typically used lambert equal area projections in the past, but I am trying to make an image using the Geostationary satellite view projection (+proj="geos"). When I do this, the United States is missing.

I am attaching reproducible code and images illustrating the issue. The "geos" projection shows the missing US polygon, while it is present in the version of the image made with the "laea" projection.

Thanks!
-Teresa

```

library("tidyverse") # version 2.0.0
library("rnaturalearth") # version 1.0.1
library("rnaturalearthdata") # version 0.1.0
library("sf") # version 1.0-14

world <- ne_countries(continent = c("north america","south america"), scale = "medium", returnclass = "sf")
  worldGeos <- st_transform(world, crs="+proj=geos +h=35785831.0 +lat_0=45 +lon_0=-90.476194 +sweep=y")
  worldLaea <- st_transform(world, crs="+proj=laea +lat_0=-30 +lon_0=-90.476194 +x_0=4321000 +y_0=3210000 +ellps=WGS84 +units=m +no_defs")
  
  ggplot(data = worldGeos) +
    geom_sf(color = "lightgray", fill = "lightgray") +
    ggtitle("Geostationary Satellite View")
  
  ggplot(data = worldLaea) +
    geom_sf(color = "lightgray", fill = "lightgray") +
    ggtitle("Lambert Azimuthal Equal Area")
  ```
![image](https://github.com/ropensci/rnaturalearth/assets/35701568/44737b47-f262-44d1-aa82-3dcee6888619)

**Comment by PMassicotte** [comment]
I am also getting the same results. I am asking around for some pointer and I will get back to you.

**Comment by TeresaPegan** [comment]
That does indeed work for me, thank you!
I think it makes sense to leave the issue open for now, since the underlying bug remains?

**Comment by PMassicotte** [comment]
I am not sure if it is a bug of `sf` or the underlying implementation. Tagging @edzer to get insights from a pro :)

**Comment by PMassicotte** [comment]
Much simpler solution (credit to @mdsumner)

``` r
library(ggplot2)
library(rnaturalearth)
library(sf)
#> Linking to GEOS 3.12.1, GDAL 3.8.0, PROJ 9.2.0; sf_use_s2() is TRUE

world <- ne_countries(
  continent = c("north america", "south america"),
  scale = "medium",
  returnclass = "sf"
)

world <- st_cast(world, "POLYGON")
#> Warning in st_cast.sf(world, "POLYGON"): repeating attributes for all
#> sub-geometries for which they may not be constant

worldGeos <- st_transform(
  world,
  crs = "+proj=geos +h=35785831.0 +lat_0=45 +lon_0=-90.476194 +sweep=y"
)
ggplot(data = worldGeos) +
  geom_sf(color = "lightgray", fill = "lightgray") +
  ggtitle("Geostationary Satellite View")
```

![](https://i.imgur.com/nmpBE9r.png)

<sup>Created on 2024-02-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
