### ISSUE TITLE
Country polygons with longitudinal coordinates outside (-180, 180)

### ISSUE THREAD

**Issue by stephanie-stewart** [ropensci/rnaturalearth#108]
I am trying to use the country polygons as an input to another function that checks to make sure that all the coordinates are in the appropriate range. Using ne_countries() is currently getting flagged as being outside of that range. I'm not totally sure why this would be happening, but I am also struggling to identify an easy fix. The issue is illustrated in the following: 

`library(rnaturalearth) `
`country_poly <- ne_countries() `
`poly_xmax <- raster::extent(country_poly)@xmax`
`poly_xmax > 180 # Evaluates to True`
`poly_xmax > 180.00000000000001 # Evaluates to True`
`poly_xmax > 180.0000000000001 # Evaluates to False` 

I don't know if this is something that would make sense/be possible to fix upstream to avoid any similar issues in the future.

**Comment by PMassicotte** [comment]
I do not have the same results as you do, probably related to how floats are represented on your computer (https://en.wikipedia.org/wiki/IEEE_754).  

However, at that many level of decimals, you are around the nanometer precision:

decimal
places   degrees          distance
-------  -------          --------
9        0.000000001      111  μm
10       0.0000000001     11.1 μm
11       0.00000000001    1.11 μm
**12       0.000000000001   111  nm
13       0.0000000000001  11.1 nm**

https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude

**Comment by stephanie-stewart** [comment]
Thanks for the clarification. That makes sense, and the concern I have is not so much about the accuracy of the measurement, it is just that the function I am trying to use won't run so long as poly_xmax is greater than 180 by any amount. I am guessing the easiest way around this would be to use a very small inward buffer?

**Comment by PMassicotte** [comment]
Which function are you trying to use? Maybe you could try to round the coords to the xx decimals?

**Comment by PMassicotte** [comment]
@stephanie-stewart Please re-open the issue if you need.
