### ISSUE TITLE
incorrect country borders

### ISSUE THREAD

**Issue by Geronticus-eremita** [ropensci/rnaturalearth#110]
It is not a coding bug I wish to report, but rather a wish for an adjustment. Given that there are a number of politically debatable cases of National borders, it would be just great to have these areas included as independent shapes, to enable graphic adjustments. This holds true e.g. for the Crimea, Kosovo or Palestine. In the current state, where these areas are predefined as belonging to neighbouring countries, the whole map is somehow problematic to work with.

**Comment by PMassicotte** [comment]
We are not manipulating/changing the data. This package just provides an interface to download data produced on https://www.naturalearthdata.com/. 

Please report any data requests or potential errors there.
