### ISSUE TITLE
Addition of missing Islands and small countries 

### ISSUE THREAD

**Issue by Rohit-Satyam** [ropensci/rnaturalearth#112]
I am using this R package for the first time to plot dengue cases. I see that the following countries are missing from the world map (usually small islands) and Singapore too

```
Barbados       
Saint Kitts and Nevis
Maldives
Saint Martin
Saint Vincent and the Grenadines
Singapore
Nauru
Kiribati
Cook Islands
```

**Comment by Nowosad** [comment]
Hi @Rohit-Satyam -- this package is allows to interact with the datasets from https://www.naturalearthdata.com/. Thus, any issues related to the data inself should be mention there.

**Comment by PMassicotte** [comment]
See also https://github.com/ropensci/rnaturalearth?tab=readme-ov-file#errors-in-the-data
