### ISSUE TITLE
iso code from package countrycode

### ISSUE THREAD

**Issue by espinielli** [ropensci/rnaturalearth#15]
It could be useful to consider usage of [R package `countrycode`](https://cran.r-project.org/web/packages/countrycode/index.html) for the implementation of "Potential additional data"/"dataframe with ISO3 and country synonyms"

**Comment by cjyetman** [comment]
I could probably help with that here and/or in [rworldmap](https://github.com/AndySouth/rworldmap)

[countrycode repo is here](https://github.com/vincentarelbundock/countrycode) @vincentarelbundock is the maintainer
