### ISSUE TITLE
Initial install

### ISSUE THREAD

**Issue by NickEWilliams** [ropensci/rnaturalearth#17]
Hi, 

Excited to play around with the package. Possibly an error on my end, but it seems that the current set up for first time installation has some issues with auto installing the dependencies, specifically httr and DBI. 
Errors:
- Installation failed: there is no package called ‘httr’
and 
- Error: package or namespace load failed for ‘rnaturalearth’:
 - object ‘dbExecute’ is not exported by 'namespace:DBI'

I manually installed both and am now up and running.

- Nick

**Comment by PMassicotte** [comment]
Closing this as it seems outdated. Please open a new issue if you still have problems.
