### ISSUE TITLE
breakaway_disputed_areas at scale10 is HTTP 404

### ISSUE THREAD

**Issue by econandrew** [ropensci/rnaturalearth#19]
Because as of right now the file is actually called

`ne_10m_admin_0_disputed_areas.zip`

without the `breakaway_`, inconsistent with other scales.

The workaround is to give the type as `admin_0_disputed_areas` and ignore the warnings.

**Comment by PMassicotte** [comment]
Closing this as it seems outdated. Please open a new issue if you still have problems.
