### ISSUE TITLE
transfer to ropensci

### ISSUE THREAD

**Issue by maelle** [ropensci/rnaturalearth#20]
:wave: @AndySouth we no longer transfer onboarded packages to ropenscilabs but instead directly to ropensci so we should move this repo. Are you ok with my doing it? If so when would you have the time to update all links? I wouldn't transfer before you have time to do that, and it's not urgent to transfer anyway.

I see these two repos would need to be transferred at the same time:

* https://github.com/ropenscilabs/rnaturalearthdata

* https://github.com/ropenscilabs/rnaturalearthhires

If possible could you please add this badge to the README of `rnaturalearth` when updating CI links?
`[![Project Status: Active – The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)`

Thanks for your patience! :smiley_cat:

**Comment by AndySouth** [comment]
Thanks @maelle ! All sounds good. Can you give me a couple of weeks to look into ? I have some other updates I want to do too and I can do at the same time.

**Comment by maelle** [comment]
Yes, ping me again when you're ready! Thank you!

**Comment by maelle** [comment]
:wave: @AndySouth could we soon transfer the repo?

**Comment by AndySouth** [comment]
Thanks for the prompt @maelle, I'll update the links in the next couple of days and get back to you.

**Comment by maelle** [comment]
Cool, thank you! I can also do the transfer now, since GitHub will redirect links (whereas if you change links before the transfer, the new links will be wrong for a short while).

**Comment by maelle** [comment]
We're speaking in ropensci now, and I've transferred the two other repos. 

I'm actually at a loss reg Travis (.org /.com) cc @sckott do you know more about such transfers nowadays? Sorry.

**Comment by sckott** [comment]
Travis is moving everyone away from travis-ci.org to travis-ci.com - looks like this pkg is at https://travis-ci.com/ropensci/rnaturalearth - i imagine builds will be done there

**Comment by sckott** [comment]
nevermind, it's still at dot org https://travis-ci.org/ropensci/rnaturalearth/builds looks like it will be later in year when moves to dot com
