### ISSUE TITLE
Supplemental river and lake centerlines not available

### ISSUE THREAD

**Issue by mps9506** [ropensci/rnaturalearth#23]
Thank you for the wonderful package. 

I am not able to download the [10m river and lake centerline North American supplemental file](https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-rivers-lake-centerlines/).

```r
check_data_exist(scale = 10, category = "physical", type = "rivers_north_america")
```
Returns:
```
[1] FALSE
Warning message: In check_data_exist(scale = 10, category = "physical", 
type = "rivers_lake_north_america") :   rivers_north_america seems not to be in the list 
for category=physical maybe try the other category of c('cultural', 'physical')
```

The file location is: https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_rivers_north_america.zip

The regular rivers_lake_centerline download works for me, but is not the file I'm after:
```r
check_data_exist(scale = 10, category = "physical",  type = "rivers_lake_centerlines")
```

Any insight would be appreciated. Cheers.

**Comment by AndySouth** [comment]
Thanks, well spotted !

The warning should now be fixed in the github version (there is a table of available layers and that wasn't in it).

Even in the CRAN version this should still work even though it does give a warning (it tries to download even if not in the table):
rivers <- ne_download(scale = 10, category = "physical", type = "rivers_north_america")

(Note not 'rivers_lake_north_america')

I'll have a look at cleaning up what happens with the warnings generally.

**Comment by mps9506** [comment]
Thanks! Works perfectly.
This might be covered already (or should be a new issue), is there a way to load `data_list_physical.csv` as a dataframe? As a user it would be easier to inspect a dataframe in R to get the filename than load the website and navigate to the file. Furthermore, having the .csv update dynamically might reduce potential issues in the future.
If that would be useful I can work up a pull request.

**Comment by AndySouth** [comment]
Good idea Michael, feel free to submit as a new issue or PR and I can look
at next week. I had thought in past that it would be good to get the list
of available data automatically from the natural earth website but there
didn't seem to be an obvious way of doing. Open to suggestions.
