### ISSUE TITLE
us county shapefile? 

### ISSUE THREAD

**Issue by floswald** [ropensci/rnaturalearth#26]
hi there, 

i was trying to get a shapefile with usa counties delineated. is there anything like this available in this package? thanks

**Comment by mps9506** [comment]
Natural Earth does not have shapefiles for that level of administrative unit available. I'm not sure if that is something planned or not. The [`tidycensus`](https://github.com/walkerke/tidycensus) package is pretty handy way of getting counties into R as a simple feature.

**Comment by floswald** [comment]
yes that was a stupid question... the tigris package has `counties()`

thanks
