### ISSUE TITLE
Is or isn't Crimea part of Russia?

### ISSUE THREAD

**Issue by fzenoni** [ropensci/rnaturalearth#27]
This is not (only) a political issue, but rather a call for consistency in the `rnaturalearth` database.

Indeed, this is what happens at the `small` scale.

```r
library(ggplot2)
library(sf)
library(rnaturalearth)

ggplot() + 
  geom_sf(data=ne_countries(scale='small', returnclass = 'sf'), size = 0.2) + 
  geom_sf(data=ne_countries(scale = 'small', country = 'Russia', returnclass = 'sf'), fill = 'red') +
  coord_sf(xlim = c(25,45), ylim = c(40,50))

``` 
![image](https://user-images.githubusercontent.com/6040873/58093597-173f9380-7bcf-11e9-8c34-b0f9153ae26b.png)

And this is what happens at the `medium` and `large` level.

![image](https://user-images.githubusercontent.com/6040873/58093618-29b9cd00-7bcf-11e9-87de-9014694c47bb.png)
![image](https://user-images.githubusercontent.com/6040873/58093635-350cf880-7bcf-11e9-9550-392ce388d3b9.png)

The reason can't simply be that Crimea is a small area disregarded by the `small` scale, as Kaliningrad Oblast is correctly included at all levels, despite having a smaller surface than Crimea (15000 vs 27000 km²).

![image](https://user-images.githubusercontent.com/6040873/58093930-d7c57700-7bcf-11e9-9304-34db1c17c76b.png)

I am in no position to suggest the best action to take. I can only suggest to have a look at the solution proposed by [the OpenStreetMap Data Working Group](https://wiki.osmfoundation.org/wiki/Working_Group_Minutes/DWG_2014-06-05_Special_Crimea) or [to simply follow the relevant UN resolution](https://en.wikipedia.org/wiki/United_Nations_General_Assembly_Resolution_68/262).

**Comment by fzenoni** [comment]
Maybe related to https://github.com/ropensci/rnaturalearth/issues/19?

**Comment by mps9506** [comment]
@fzenoni I'm not the package maintainer, but my thoughts are that this package only provides an interface to access Natural Earth data. I think the best recourse is to report the discrepancies to the Natural Earth maintainers: https://www.naturalearthdata.com/corrections/
