### ISSUE TITLE
Missing countries from the data set

### ISSUE THREAD

**Issue by aveshenpillay** [ropensci/rnaturalearth#31]
Would it be possible to include / update for the inclusion of the following countries in the data set? I cannot see them in the following call:

`world_map <- ne_countries(returnclass = "sf")`

Country | ISO3 Code
-- | --
Andorra | AND
Antigua and   Barbuda | ATG
Bahrain | BHR
Barbados | BRB
Cabo Verde | CPV
Dominica | DMA
Grenada | GRD
Holy See | VAT
Kosovo | XKX
Liechtenstein | LIE
Maldives | MDV
Malta | MLT
Mauritius | MUS
Monaco | MCO
Saint Kitts   and Nevis | KNA
Saint Lucia | LCA
Saint   Vincent and the Grenadines | VCT
San Marino | SMR
Seychelles | SYC
Singapore | SGP

**Comment by mps9506** [comment]
Try the following:

```r
world_map <- ne_countries(scale = 50, returnclass = 'sf')
```

This should return all the countries in your list. However, the ISO3 code in the dataset for Kosovo is KOS.

**Comment by aveshenpillay** [comment]
Worked perfectly, thank you!
