### ISSUE TITLE
Italy - changes in provinces in Sardegna region

### ISSUE THREAD

**Issue by RamiKrispin** [ropensci/rnaturalearth#33]
Hi,

I am working with Italy data, and I noticed that the provinces of Sardegna region in Italy are not updated:

```
> italy_map <- rnaturalearth::ne_states(country = "Italy", returnclass = "sf") %>%
    dplyr::filter(region == "Sardegna")
> italy_map$name %>% unique %>% sort
[1] "Cagliari"          "Carbonia-Iglesias" "Medio Campidano"   "Nuoro"            
[5] "Ogliastra"         "Olbia-Tempio"      "Oristrano"         "Sassari" 
```

On 2016, the provinces Carbonia-Iglesias, Medio Campidano, and some part of Cagliari were merged into new province - South Serdinia (source (Wikipodia)[https://en.wikipedia.org/wiki/Province_of_South_Sardinia]).

Therefore, when plotting Italy provinces, with the new provinces setting, this is the results:

![image](https://user-images.githubusercontent.com/12760966/80280318-2de04b80-86b8-11ea-9b5e-cb430722791e.png)

Thanks,
Rami

**Comment by Nowosad** [comment]
@RamiKrispin I believe that the **rnaturalearth** package is just an interface for the data from https://www.naturalearthdata.com/. You probably should point them to this problem using https://www.naturalearthdata.com/issues/.

**Comment by RamiKrispin** [comment]
Thanks, will do
