### ISSUE TITLE
South American continent incorrectly includes Central America

### ISSUE THREAD

**Issue by RussellGrayxd** [ropensci/rnaturalearth#35]
library(rnaturalearth)
library(sp)
#world countries
sDPF <- ne_countries()
sPDF.SA <- subset(sPDF, continent == "South America")
plot(sPDF.SA)

This subset includes Central America which is part of North America, not South America.

**Comment by PMassicotte** [comment]
Seems to be working properly in the current version of the package. Please feel free to reopen if you still experience issues.

![image](https://user-images.githubusercontent.com/4519221/216790845-7b48bdb0-e5c6-4c16-87de-de425e51bb0e.png)
