### ISSUE TITLE
install of hires data glitch...

### ISSUE THREAD

**Issue by ryanpeek** [ropensci/rnaturalearth#37]
Hi, great package, just wanted to mention a glitch in installing the hires data...

When running the following code:
`mex_sf <- ne_states(country="Mexico", returnclass = "sf")` 

I'm asked to install the hires data...but upon trying to do so I get an error message: "Connection not found".

I went to this repo and followed the readme code:
```
install.packages("rnaturalearthhires",
                 repos = "http://packages.ropensci.org",
                 type = "source")
```

This also didn't work. I got several different error messages but largely centered around "no connection". 

When using the following, everything installs without any trouble:
`devtools::install_github("ropensci/rnaturalearthhires")`

Suggest editing the README so the install info matches the above. I'm not sure why the other option via `install.packages` breaks, but with devtools no problem. 

I'm using R 4.0.3, on Mojave 10.14.6 and have the most updated {sf} and {rnaturalearth} versions.

**Comment by jaseeverett** [comment]
I had the same problem on macOS Big Sur. Installing from GitHub worked perfectly. Thanks for the tip. 
`devtools::install_github("ropensci/rnaturalearthhires")`

**Comment by andysouth** [comment]
Thanks @ryanpeek @jaseeverett 

Strange, I've just checked on windows and this does work for me.

`install.packages("rnaturalearthhires",
                 repos = "http://packages.ropensci.org",
                 type = "source")`

@sckott do you know a reason why that doesn't work on macOS ?

**Comment by sckott** [comment]
Not sure why that install using packages.ropensci.org didn't work. worked for me, but i'm not on big sur yet. There's also `install.packages("rnaturalearthhires", repos = "https://dev.ropensci.org")` - that should have binaries for windows/macos

**Comment by jaseeverett** [comment]
Hmm. Very weird. I just tried again and it works for me now. I tried on about 3 seperate occasions last week and it wouldn't work. Thanks for looking into it @sckott and @andysouth

**Comment by ryanpeek** [comment]
Same, I'm on Mojave still and it worked just now when I tried. Something has been updated or is now correctly linked. I'll close this issue now. Thanks all!
