### ISSUE TITLE
rnaturalearth installation error

### ISSUE THREAD

**Issue by aveshenpillay** [ropensci/rnaturalearth#41]
Good day, I tried a function call using `ne_countries` and got the could not find function error. I then tried to install rnaturalearth, but that gave me another error. Screen shots of the error and my system specs are attached. Thanks!

<img width="429" alt="Screenshot 2020-12-03 at 00 57 50" src="https://user-images.githubusercontent.com/27091888/100941806-e8fc7d00-3502-11eb-8a02-37d529852cd2.png">
<img width="894" alt="Screenshot 2020-12-03 at 00 58 43" src="https://user-images.githubusercontent.com/27091888/100941812-ebf76d80-3502-11eb-9597-950789730476.png">
<img width="323" alt="Screenshot 2020-12-03 at 00 58 52" src="https://user-images.githubusercontent.com/27091888/100941814-edc13100-3502-11eb-9350-51d085c70650.png">

**Comment by apal90** [comment]
I am having the same problem. The function worked for me the first time after installation. But after I restarted RStudio, I kept getting this error. Any solutions?

**Comment by s2t2** [comment]
I have tried so many different strategies to just install this package, but it never succeeds.

**Comment by PMassicotte** [comment]
This is an issue with `sf` installation, which looks like can not be compiled on your system due to missing libraries. I would suggest having a look at `sf` installation.
