### ISSUE TITLE
'ne_download': check if map already exists in 'destdir'

### ISSUE THREAD

**Issue by AMBarbosa** [ropensci/rnaturalearth#50]
It could save a lot of time and energy if `ne_download` first checked if a file is already in 'destdir' before downloading it. If it is, the function could just import the map that's already there. (Or you could add an argument to optionally re-download and overwrite the map if explicitly wanted.) Cheers!

**Comment by plantarum** [comment]
This is marked as completed, but I'm a little confused about how it works.  From my experiments and reading the code, I think the options work like this:

1. `ne_download(load = TRUE, ...)` will *always* download the file from naturalearth - it doesn't check if the file already exists, and it doesn't save anything
2. `ne_download(load = FALSE, destdir = "DL", ...)` will *always* download the file from naturalearth and save a copy in "DL". It doesn't check if the file already exists, and it doesn't load the file into R.
3. `ne_load(destdir = "DL", ...)` will load a previously downloaded file if it exists.

I have the same request as @AMBarbosa : it would be nice if a single function could be used to download, save a local copy, and load a copy into R. This is how functions like `geodata::gadm` work. In that case, you use the same code for all three actions. As an example:

```
bel <- gadm(country="BEL", level=1, path="DL")
```

When this code is evaluated, it checks if the data exists in "DL". If it doesn't, it downloads it and saves it there. It will then read the local copy into R in the object `bel`. This means no matter what state you start in, after running the function you will have a local copy of the map on your computer, and it will be loaded into memory as well; and it won't download data you already have.

This is very convenient for sharing scripts among computers or different people, as your code works the same the first time as it does the second and subsequent times. If I understand the `rnaturalearth` approach, you would need to do something like this:

```
if(file.exists("DL/map"){
  ne_load("map", destdir = "DL") 
} else {
  ne_download("map", load = FALSE, destdir = "DL")
  ne_load("map", destdir = "DL") 
}
```

I understand you might want to use all these steps in different use cases, but it would be nice if there were options available to allow the 'one line' approach from geodata to be used with rnaturalearth.

**Comment by PMassicotte** [comment]
Hi and thank you for reaching out. Would this behaviour be ok:
 
- `ne_download(type = "countries", scale = 110)` - current behavior: download to memory only
-  `ne_download(type = "countries", scale = 110, destdir = "DL")` - NEW: check cache in "DL", download & save if missing, load into R
-  `ne_download(type = "countries", scale = 110, load = FALSE, destdir = "DL")` - current behavior: always download and save
