### ISSUE TITLE
is there a way to retrieve a country 'middle point'?

### ISSUE THREAD

**Issue by sghignone** [ropensci/rnaturalearth#55]
In a ggplot plot based on whole world map, I'd like to place a geom_point (with size proportional to a variable) at a coordinate representing the 'center' of a selected list of countries. Is there a way to get the country middle point easily?
Thanks

**Comment by mps9506** [comment]
Use the `st_point_on_surface()` function in sf.

```r
library(rnaturalearth)
library(sf)
library(purrr)
library(dplyr)
library(ggplot2)

countries <- ne_countries(returnclass = "sf")

countries_center <- st_point_on_surface(countries)

ggplot() +
  geom_sf(data = countries) +
  geom_sf(data = countries_center,aes(size = pop_est), color = "steelblue")
```

![image](https://user-images.githubusercontent.com/11282246/167918076-4454fb9f-0e97-40a2-8459-7b875b727386.png)

**Comment by PMassicotte** [comment]
Closing this since it is not related to `rnaturalearth` but rather on `sf` and general geo-computational manipulations.
