### ISSUE TITLE
South Sudan  data missing

### ISSUE THREAD

**Issue by mesfind** [ropensci/rnaturalearth#56]
ssudan_sf <- ne_states(country = "South Sudan", returnclass = "sf")

Error in ne_states(country = "South Sudan", returnclass = "sf") : 
  No such country (South Sudan) in the data

**Comment by PMassicotte** [comment]
@mesfind Is this data available here: https://www.naturalearthdata.com/

**Comment by mps9506** [comment]
South Sudan is in the following dataset:

```r
south_sudan <- ne_countries(type = "countries", returnclass = "sf") |> 
  filter(admin == "South Sudan")
```
