### ISSUE TITLE
New Maintainer Wanted

### ISSUE THREAD

**Issue by maelle** [ropensci/rnaturalearth#62]
Or new maintainer team. :smile_cat: 

The following issues would need to be solved

- Fixing the code connecting to a data source see #29 and #61
- Updating dependencies so a bit of refactoring see #60 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

Cc @andysouth @ropensci/admin @z3tt

**Comment by khufkens** [comment]
Will look into #60 as I use the package too often and I'm doing the same for a number of my packages.

Won't take over maintenance as this is soulless task which provides little or no credit or joy for that matter. 

FYI. ropensci should invest more in this instead of the user facing component IMO. No maintainer = no software = no users

**Comment by PMassicotte** [comment]
I do not mind giving a hand :)

**Comment by opus1993** [comment]
How can I help?

**Comment by maelle** [comment]
@khufkens thanks a lot for #63!

@PMassicotte @opus1993 Thank you! Do you want write access to the repository to review and merge @khufkens' PR to begin with? Does one of you want to become the maintainer (you could be co-maintainers as well)?

**Comment by maelle** [comment]
@defuneste thanks for your contribution in #63! Are you interested in contributing further?

**Comment by PMassicotte** [comment]
I do not mind being a maintainer or being part of the maintainer team :)

**Comment by defuneste** [comment]
Hi @maelle Thank a lot for your work for Ropensci! I do not think I have the skills to do that , I am slowly reading `R packages` and the Ropensci `rOpenSci Packages book`. If you are aware of some "mentor ship" or a way to learn/observe from experienced user I will be interested.

**Comment by maelle** [comment]
@defuneste Ok, thank you! You might be interested in some of the packages looking for co-maintainers https://ropensci.org/blog/2022/10/17/maintain-or-co-maintain-an-ropensci-package/#packages-looking-for-co-maintainers or the issues labelled help-wanted https://ropensci.org/help-wanted/

(I'll then hide your and my comment as off-topic :-) )

**Comment by andysouth** [comment]
Hi @PMassicotte @defuneste @khufkens @maelle 

Many thanks for your help and offers. Apologies I have been quiet. I haven't been working in this area for a little while and I was struggling to keep up. Also my package workflows are rusty !

@PMassicotte would you like to take over as primary maintainer and I can help out as needed ? It would be much appreciated.

**Comment by andysouth** [comment]
Hello @mps9506 You've been really good at responding to issues (better than me). I wonder if you might want to contribute to package maintenance in future and be mentioned as such ?

**Comment by PMassicotte** [comment]
Hi @andysouth that would be a great pleasure! Let me know how you want to make it work :)

Cheers,
Phil

**Comment by andysouth** [comment]
Thanks @PMassicotte Philippe,
Would you be OK to take on the submission to CRAN ? I can indicate you as the maintainer and perhaps @maelle can give you write access to the repo ?
Andy

**Comment by maelle** [comment]
@andysouth I've even given admin access to @PMassicotte as we do these days for maintainers. :-)

**Comment by andysouth** [comment]
Many thanks @maelle :-)

**Comment by PMassicotte** [comment]
Should we first submit the current version as it solve borken URLs?

**Comment by andysouth** [comment]
Seems like a good idea :-) Unless people come back strongly and quickly with responses to #65. I'm just about to merge the PR.

**Comment by defuneste** [comment]
@andysouth No need or me and thx for the package!

**Comment by mps9506** [comment]
@andysouth happy to assist as needed. 👍🏽
