### ISSUE TITLE
Issue with ne_download

### ISSUE THREAD

**Issue by cecile-meier-scherling** [ropensci/rnaturalearth#70]
Hello, I am trying to run the following code:
admin8 <- ne_download(scale="large", type = "admin_1_states_provinces_lines",
                      category = "cultural", returnclass = "SF")

However, I run into the following error: 
Warning: admin_1_states_provinces_lines seems not to be in the list for category=cultural maybe try the other category of c('cultural', 'physical')Warning: admin_1_states_provinces_lines seems not to be in the list for category=cultural maybe try the other category of c('cultural', 'physical')trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip'
Warning: cannot open URL 'https://www.naturalearthdata.com/http/www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip': HTTP status was '404 Not Found'Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip'

It seems like there is an issue with the URL. Has anyone else encountered this issue?

**Comment by PMassicotte** [comment]
Hi.

It is fixed in the dev version of the package. You can install it from GitHub to solve your issue. CRAN version is cumming soon!

**Comment by cecile-meier-scherling** [comment]
Hello @PMassicotte thank you for your response. 

I have uninstalled rnaturalearth, and then reinstalled it with the following line `devtools::install_github("ropensci/rnaturalearth")`

However, when I run the following line:
```
admin8 <- ne_download(scale="large", type = "admin_1_states_provinces_lines",
                      category = "cultural", returnclass = "sf")
```

I now get the following error again:
```
Warning: admin_1_states_provinces_lines seems not to be in the list for category=cultural maybe try the other category of c('cultural', 'physical')Warning: admin_1_states_provinces_lines seems not to be in the list for category=cultural maybe try the other category of c('cultural', 'physical')trying URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip'
Warning: cannot open URL 'https://www.naturalearthdata.com/http/www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip': HTTP status was '404 Not Found'Error in utils::download.file(file.path(address), zip_file <- tempfile()) : 
  cannot open URL 'http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_admin_1_states_provinces_lines.zip'
```

**Comment by PMassicotte** [comment]
Have you closed and re-opened R?

**Comment by PMassicotte** [comment]
```r
r$> admin8 <- ne_download(
+   scale = "large", type = "admin_1_states_provinces_lines",
+   category = "cultural", returnclass = "sf"
+ )
trying URL 'https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_1_states_provinces_lines.zip'
Content type 'application/zip' length 5993148 bytes (5.7 MB)
==================================================
downloaded 5.7 MB
```

**Comment by cecile-meier-scherling** [comment]
Yes, that fixed it - thank you!
