### ISSUE TITLE
Malta data missing

### ISSUE THREAD

**Issue by leonardofwink** [ropensci/rnaturalearth#71]
Hi!
Today I was trying to find the correct country in Worldle using this [guide](https://www.jaredlander.com/2022/03/using-r-to-win-worldle/), but i couldn't find Malta's data.

Here's what I've tried: 

`library(dplyr)`
`data(countries110, package = "rnaturalearth")`

`countries <- countries110 %>% `
`  st_as_sf()`

`countries %>% `
`  dplyr::select(SUBUNIT) %>% `
`  filter(`
`    SUBUNIT == "Malta"`
 ` )`

And here's what I found:

`Simple feature collection with 0 features and 1 field`
`Bounding box:  xmin: NA ymin: NA xmax: NA ymax: NA`
`CRS:           +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0`
`[1] SUBUNIT  geometry`
`<0 linhas> (ou row.names de comprimento 0)`

**Comment by PMassicotte** [comment]
`rnaturalearth` provides an interface to https://www.naturalearthdata.com/. Can you verify that the requested data is on their website?

**Comment by mps9506** [comment]
You can find Malta in the following dataset:

```r
countries <- ne_countries(type = "tiny_countries", returnclass = "sf")
```

**Comment by PMassicotte** [comment]
So it is not missing?
