### ISSUE TITLE
Add Remotes field for rnaturalearthhires?

### ISSUE THREAD

**Issue by maelle** [ropensci/rnaturalearth#73]
We see https://github.com/r-universe/ropensci/actions/runs/4091518554/jobs/7055696202 via https://ropensci.r-universe.dev/builds

```r
Failed with error:  ‘there is no package called ‘rnaturalearthhires’’
```

**Comment by PMassicotte** [comment]
As I understand, CRAN packages can not have the "Remotes" field. 

https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

Any suggestions?

**Comment by maelle** [comment]
oh right but for the docs building you need this field, or to pre-build the vignette as shown in this post by @jeroen https://ropensci.org/blog/2019/12/08/precompute-vignettes/

**Comment by maelle** [comment]
friendly reminder :smile_cat:

**Comment by PMassicotte** [comment]
I have been working on it, but I am trying to find a solution that do not involve renaming the vignette files. Would not be a better solution to use the Additional Repo field like CRAN does? (https://github.com/ropensci/rnaturalearth/blob/3090745b3829c3cad2747c713cab048f01c78238/DESCRIPTION#L33)?

**Comment by maelle** [comment]
yes that might work? https://community.rstudio.com/t/correctly-installing-non-cran-dependencies/114649/6

**Comment by PMassicotte** [comment]
I am not sure to understand. Would it work if I install it manually with Actions?

**Comment by maelle** [comment]
no I mean the `Additional_repositories` would work for CRAN if the package is used conditonally.

Now you can also make sure it's installed on rOpenSci docs server by adding this to DESCRIPTION:

```
Config/Needs/website:  ropensci/rnaturalearthhires
```

**Comment by PMassicotte** [comment]
But I think this will break CRAN? They allow having this field in the DESCRIPTION file?

**Comment by maelle** [comment]
the `Config/Needs/website` field will be fine (ignored) on CRAN https://r-pkgs.org/description.html#sec-description-custom-fields

**Comment by PMassicotte** [comment]
oh ok. I did that, its building. Lets see if it works :)

**Comment by PMassicotte** [comment]
Looks like the `rnaturalearthhighres` is installing, but I am getting another error and I can not find why: https://github.com/r-universe/ropensci/actions/runs/4384887842/jobs/7676906560#step:3:1140

Any idea?

**Comment by maelle** [comment]
weird, let me try a local build

**Comment by PMassicotte** [comment]
I tried to run `rotemplate:::build_ropensci_docs()` locally, I am also getting an error.

**Comment by maelle** [comment]
I am still installing deps :sweat_smile:

**Comment by maelle** [comment]
I can reproduce the error with `pkgdown::build_site()` :eyes:

**Comment by PMassicotte** [comment]
Same, and the error message is cryptic.

**Comment by maelle** [comment]
https://stackoverflow.com/questions/75117053/how-to-successfully-use-pkgdown-when-svglite-graphics-device-is-used

**Comment by PMassicotte** [comment]
oh... might just switch to png then. Let me try.

**Comment by jeroen** [comment]
Also you should move images used in `README.md` to `man/figures`.

**Comment by maelle** [comment]
@jeroen #75 :wink:

**Comment by PMassicotte** [comment]
@jeroen I just did it last commit :)

**Comment by jeroen** [comment]
Ok great :)

**Comment by PMassicotte** [comment]
I think this is fixing everything, thank yo @maelle and @jeroen for helping.

**Comment by maelle** [comment]
Awesome, great to read, well done!
