### ISSUE TITLE
Can't access website

### ISSUE THREAD

**Issue by eteitelbaum** [ropensci/rnaturalearth#76]
I get a 404 error when I try to access the github pages [site](http://ropensci.github.io/rnaturalearth/) for the `rnaturalearth` package.

**Comment by PMassicotte** [comment]
Tx, I will check that. Meanwhile: https://github.com/ropensci/rnaturalearth/

**Comment by PMassicotte** [comment]
This is not something we control. Contact datacamp if you want it fixed.

**Comment by eteitelbaum** [comment]
OK but currently you feature the link to it on your [github page](https://github.com/ropensci/rnaturalearth)
