### ISSUE TITLE
Add rnaturalearthdata as a dependency

### ISSUE THREAD

**Issue by szimmer** [ropensci/rnaturalearth#84]
Rather than installing while running code, add the package as a dependency. This works better with usage of renv and probably other package maintainers as loading of the package is explicitly needed or it needs to be in dependency.

**Comment by szimmer** [comment]
I installed it from CRAN in my workflow and this works just fine. https://cran.r-project.org/web/packages/rnaturalearthdata/index.html

**Comment by PMassicotte** [comment]
I just realized that is it already in `Suggests`. As it is not mandatory, any reasons to move it in `Imports` ?
