### ISSUE TITLE
`ne_download()` should not warn about `sp` for raster objects or if `load = FALSE` 

### ISSUE THREAD

**Issue by eliocamp** [ropensci/rnaturalearth#97]
`ne_download()`'s `returnclass` argument is only relevant if `load = TRUE` and `category != "raster"`, so throwing a warning in other cases might not be relevant. Maybe this

https://github.com/ropensci/rnaturalearth/blob/704772792ecafb0f29b9f68089fdab80ccf4cb43/R/ne_download.R#L99-L101

could be something like this

```r
warn <- returnclass == "sp" & load & category == "raster"
  if (warn) {
    deprecate_sp("ne_download(returnclass = 'sp')")
  }
```

**Comment by PMassicotte** [comment]
Fixed, thank you
